// GENERATED by @edgedb/generate v0.5.6

import type {Executor} from "edgedb";

export type UpdateCardArgs = {
  readonly "cardId": string;
  readonly "front": string;
  readonly "back": string;
};

export type UpdateCardReturns = {
  "id": string;
} | null;

export function updateCard(client: Executor, args: UpdateCardArgs): Promise<UpdateCardReturns> {
  return client.querySingle(`\
with
  cardId := <uuid>$cardId,
  front := <str>$front,
  back := <str>$back,
update Card
filter .id = cardId
set {
  front := front,
  back := back,
};`, args);

}
