// GENERATED by @edgedb/generate v0.5.6

import type {Executor} from "edgedb";

export type GetDeckArgs = {
  readonly "deckId": string;
};

export type GetDeckReturns = {
  "id": string;
  "name": string;
  "description": string | null;
  "cards": Array<{
    "id": string;
    "front": string;
    "back": string;
  }>;
} | null;

export function getDeck(client: Executor, args: GetDeckArgs): Promise<GetDeckReturns> {
  return client.querySingle(`\
with deckId := <uuid>$deckId,
select Deck {
  id,
  name,
  description,
  cards: {
    id,
    front,
    back,
  },
} filter .id = deckId`, args);

}
