// GENERATED by @edgedb/generate v0.5.6

import type {Executor} from "edgedb";

export type CreateDeckArgs = {
  readonly "name": string;
  readonly "description"?: string | null;
  readonly "cards": ReadonlyArray<{
  readonly "front": string;
  readonly "back": string;
}>;
};

export type CreateDeckReturns = {
  "id": string;
};

export function createDeck(client: Executor, args: CreateDeckArgs): Promise<CreateDeckReturns> {
  return client.queryRequiredSingle(`\
with
  name := <str>$name,
  description := <optional str>$description,
  cards := enumerate(array_unpack(<array<tuple<front: str, back: str>>>$cards)),
  DECK := (
    insert Deck {
      name := name,
      description := description,
      creator := global current_user,
    }
  ),
  CARDS := (
    for card in cards
    insert Card {
      order := card.0,
      front := card.1.front,
      back := card.1.back,
      deck := DECK,
    }
  ),
select DECK;`, args);

}
