// GENERATED by @edgedb/generate v0.5.6

import type {Executor} from "edgedb";

export type CreateUserArgs = {
  readonly "name": string;
};

export type CreateUserReturns = string;

export function createUser(client: Executor, args: CreateUserArgs): Promise<CreateUserReturns> {
  return client.queryRequiredSingle(`\
with
  name := <str>$name,
  user := (
    insert User {
      name := name,
    }
  ),
  access_token := (
    insert AccessToken {
      user := user,
      token := <str>uuid_generate_v4(),
    }
  )
select access_token.token;`, args);

}
